const ASSET_IMAGES = {
    ICON_SIGN_ITEM_SELECT: require('../assets/sign_item_select.png'),
    ICON_SIGN_ITEM_UNSELECT: require('../assets/sign_item_un_select.png'),
    ICON_SPECIAL: require('../assets/icon_special.png'),
    ICON_MY: require('../assets/icon_my.png'),
    ICON_MY_SELECT: require('../assets/icon_my_select.png'),
    ICON_LINLI: require('../assets/icon_linli.png'),
    ICON_LINLI_SLECT: require('../assets/icon_linli_un_select.png'),
    ICON_EMERGENCY: require('../assets/icon_emergency.png'),
    ICON_DAKA_SELECT: require('../assets/icon_daka.png'),
    ICON_DAKA: require('../assets/icon_daka_un_select.png'),
    ICON_TASK: require('../assets/icon_task.png'),
    ICON_TASK_SELECT: require('../assets/icon_task_select.png'),
    ICON_CUSTOM: require('../assets/icon_custom.png'),
    ICON_ADD: require('../assets/icon_add.png'),
    ICON_MORE: require('../assets/icon_more.png'),
    ICON_SIGN_SUCCESS: require('../assets/icon_sign_success.png'),
    ICON_MESSAGE: require('../assets/icon_message.png'),
    ICON_BACK: require('../assets/icon_back.png'),
    ICON_SET: require('../assets/icon_set.png'),
    ICON_ABOUT_US: require('../assets/icon_about_us.png'),
    ICON_OPINION: require('../assets/icon_opinion.png'),
    ICON_EVALUATION: require('../assets/icon_evaluation.png'),
    ICON_RECOMMEND: require('../assets/icon_recommend.png'),
    ICON_AGREE_SELECT: require('../assets/icon_agree_select.png'),
    ICON_AGREE_UN_SELECT: require('../assets/icon_agree_un_select.png'),
    ICON_SPECIAL_DEFAULT: require('../assets/icon_special_default.png'),
    ICON_HOME_TASK_ADD: require('../assets/icon_home_task_add.png'),
    ICON_ADD_FRIEND: require('../assets/icon_add_friend.png'),
    ICON_CODE_IMAGE: require('../assets/icon_code_image.png'),
    ICON_SEARCH: require('../assets/icon_search.png'),
    ICON_SPECIAL_LOCATION: require('../assets/icon_special_location.png'),
    ICON_SPECIAL_TIME: require('../assets/icon_special_time.png'),
    ICON_SPECIAL_QUESTION: require('../assets/icon_special_question.png'),
    ICON_SPECIAL_REPEAT: require('../assets/icon_special_repeat.png'),
    ICON_SPECIAL_SIGN: require('../assets/icon_special_sign.png'),
    ICON_SPECIAL_CONTRACT: require('../assets/icon_special_contract.png'),
    ICON_DELETE: require('../assets/icon_delete.png'),
    ICON_NONE: require('../assets/icon_none.png'),
    ICON_TASK_DEFAULT: require('../assets/icon_task_default.png'),
    ICON_TASK_SIGN_SUCCESS: require('../assets/icon_task_sign_success.png'),
    ICON_SELECT_CORRECT: require('../assets/icon_select_correct.png'),
    ICON_IMAGE_DELETE: require('../assets/icon_image_delete.png'),
    ICON_IMAGE_ADD: require('../assets/icon_image_add.png'),
    ICON_EMERGENCY_IMAGE_ADD: require('../assets/icon_emergency_image_add.png'),
    ICON_CONTACT_SELECT: require('../assets/icon_contact_select.png'),
    ICON_CONTACT_UN_SELECT: require('../assets/icon_contact_un_select.png'),
    ICON_HOME_NORMAL_ADD: require('../assets/icon_home_normal_add.png'),
    ICON_HOME_SPECIAL_ADD: require('../assets/icon_home_special_add.png'),
    ICON_DEFAULT_HEAD_IMAGE: require('../assets/icon_default_head_image.png'),

    IMAGE_SHOW_BG: require('../assets/image_show_bg.png'),
    IMAGE_MY_DETAIL_BG: require('../assets/image_my_detail.png'),
    IMAGE_VIP_BG: require('../assets/image_vip_bg.png'),
    IMAGE_DEFAULT_UN_LOGIN: require('../assets/image_default_headImage_un_login.png'),
    IMAGE_DEFAULT_LOGIN: require('../assets/image_login_default.png'),
    IMAGE_NONE_CONTRACT: require('../assets/image_none_contracts.png'),
    IMAGE_EMERGENCY_BG: require('../assets/image_emergency_bg.png')

}

export default ASSET_IMAGES;